### PR TITLE
Fix incorrect etag api docs

### PR DESCRIPTION
**Pull request by sergei-maertens**
Related to https://github.com/VNG-Realisatie/gemma-zaken/issues/1978

:warning: This should be also be applied to:

* master

### CODE REVIEW

**Comment by sergei-maertens** [comment]
Build is failing on something that seems unrelated?

**Comment by SonnyBA** [comment]
@sergei-maertens the build is probably failing because an update from `spectral` (that I also ran into earlier, [see issue](https://github.com/stoplightio/spectral/issues/1796)), if you add the same configuration as in [this commit](https://github.com/VNG-Realisatie/catalogi-api/commit/ee5870762caf93e2fa908c88dafa7b89d93700fd) it should be able to run properly again.

**Review by SonnyBA — APPROVED** [review]
Los van eerder toegevoegde comment ziet het er wat mij betreft goed uit

**Comment by sergei-maertens** [comment]
Fixes also applied to master in:

* c2f3e7c69d71959f12792121cda128226324cc45
* 0305705002d112d9253b20dff1782b2b7e37f82e
* 951ad509fc881b033b246ffc5054a52ad5e93712
* 4944806cf99617a6e38dbc1cf44fba7304a85086
* 99491c79fab9fd9d2995eae4ff13b14318b34f29

**Pull request merged**
